-- AlterTable
ALTER TABLE "Event" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'pending';

-- AlterTable
ALTER TABLE "User"
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "firstName" SET DEFAULT 'John',
ALTER COLUMN "lastName" SET DEFAULT 'Doe';

-- CreateTable
CREATE TABLE "HoursLog" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "action" TEXT NOT NULL,
    "hours" DOUBLE PRECISION NOT NULL,
    "performedBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "HoursLog_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "HoursLog" ADD CONSTRAINT "HoursLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;